name: Licenses Check

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: null

jobs:
  license_check:
    timeout-minutes: 15
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "Use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Checks licenses of all dependencies in lockfile
        run: |
          yarn global add license-checker-rseidelsohn
          export PATH="$(yarn global bin):$PATH"
          license-checker-rseidelsohn --onlyAllow "Apache;AAL;BSD;Artistic;" --production --excludePrivatePackages --json 
          echo $?
