name: Licenses Check

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: null

jobs:
  license_check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "Use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: "yarn"
      - name: Checks licenses of all dependencies in lockfile
        run: npx --yes license-checker-rseidelsohn --production  --excludePrivatePackages --onlyAllow "MIT;Apache;AAL;BSD;Artistic;CC0;ISC;ISCL;PostgreSQL License;Public Domain;Unlicense;UPL;W3C;WTFPL;Python;CC-;BlueOak"
